# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a6da3a7dd97c42253bf6de53abe748ae11b01a5ffaee661b5bdcec0c1c9c2a7e124d61fe346909909829f38359fba725e50bbe67cd7b18888df568a027db7bf

test:
  secret_key_base: df0448014a47610868625e72b75930a993375d3d2e8761911780f04fb7b8203a41ab8b78065d8fa27b0c72f9923ad10f97ba9c8de0d108f5a9adec50d4e8a55d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

require 'securerandom'

def secure_token
  token_file = Rails.root.join('.secret')
  if File.exist?(token_file)
    # Use the existing token.
    File.read(token_file).chomp
  else
    # Generate a new token and store it in token_file.
    token = SecureRandom.hex(64)
    File.write(token_file, token)
    token
  end
end

SampleApp::Application.config.secret_key_base = secure_token